/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FaceMarker {
  'xPercent' : number,
  'yPercent' : number,
  'faceNumber' : bigint,
}
export type PollCategory = { 'mostCharming' : null } |
  { 'mostPhotogenic' : null } |
  { 'bestSmile' : null } |
  { 'bestStyle' : null } |
  { 'mostHandsome' : null } |
  { 'mostConfident' : null } |
  { 'mostAttractive' : null };
export type PollId = string;
export interface PollPublic {
  'id' : PollId,
  'creator' : UserId,
  'expiresAt' : Timestamp,
  'votes' : Array<VoteTally>,
  'totalVotes' : bigint,
  'createdAt' : Timestamp,
  'isAnonymous' : boolean,
  'photoUrl' : string,
  'faceMarkers' : Array<FaceMarker>,
  'caption' : [] | [string],
  'category' : PollCategory,
}
export interface PollSummary {
  'id' : PollId,
  'leadingFace' : [] | [bigint],
  'expiresAt' : Timestamp,
  'totalVotes' : bigint,
  'photoUrl' : string,
  'caption' : [] | [string],
  'category' : PollCategory,
}
export interface ProfilePublic {
  'id' : UserId,
  'username' : string,
  'createdAt' : Timestamp,
  'pollCount' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface VoteTally {
  'count' : bigint,
  'faceNumber' : bigint,
  'percentage' : number,
}
export interface _SERVICE {
  'castVote' : ActorMethod<
    [PollId, bigint],
    { 'ok' : Array<VoteTally> } |
      { 'err' : string }
  >,
  'createPoll' : ActorMethod<
    [string, Array<FaceMarker>, PollCategory, bigint, [] | [string], boolean],
    { 'ok' : PollPublic } |
      { 'err' : string }
  >,
  'createProfile' : ActorMethod<
    [string],
    { 'ok' : ProfilePublic } |
      { 'err' : string }
  >,
  'getMyPolls' : ActorMethod<[], Array<PollSummary>>,
  'getMyProfile' : ActorMethod<[], [] | [ProfilePublic]>,
  'getPoll' : ActorMethod<[PollId], [] | [PollPublic]>,
  'getProfile' : ActorMethod<[UserId], [] | [ProfilePublic]>,
  'getPublicFeed' : ActorMethod<[bigint], Array<PollSummary>>,
  'getResults' : ActorMethod<[PollId], [] | [Array<VoteTally>]>,
  'hasVoted' : ActorMethod<[PollId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];