/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PollId = IDL.Text;
export const VoteTally = IDL.Record({
  'count' : IDL.Nat,
  'faceNumber' : IDL.Nat,
  'percentage' : IDL.Float64,
});
export const FaceMarker = IDL.Record({
  'xPercent' : IDL.Float64,
  'yPercent' : IDL.Float64,
  'faceNumber' : IDL.Nat,
});
export const PollCategory = IDL.Variant({
  'mostCharming' : IDL.Null,
  'mostPhotogenic' : IDL.Null,
  'bestSmile' : IDL.Null,
  'bestStyle' : IDL.Null,
  'mostHandsome' : IDL.Null,
  'mostConfident' : IDL.Null,
  'mostAttractive' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const PollPublic = IDL.Record({
  'id' : PollId,
  'creator' : UserId,
  'expiresAt' : Timestamp,
  'votes' : IDL.Vec(VoteTally),
  'totalVotes' : IDL.Nat,
  'createdAt' : Timestamp,
  'isAnonymous' : IDL.Bool,
  'photoUrl' : IDL.Text,
  'faceMarkers' : IDL.Vec(FaceMarker),
  'caption' : IDL.Opt(IDL.Text),
  'category' : PollCategory,
});
export const ProfilePublic = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'pollCount' : IDL.Nat,
});
export const PollSummary = IDL.Record({
  'id' : PollId,
  'leadingFace' : IDL.Opt(IDL.Nat),
  'expiresAt' : Timestamp,
  'totalVotes' : IDL.Nat,
  'photoUrl' : IDL.Text,
  'caption' : IDL.Opt(IDL.Text),
  'category' : PollCategory,
});

export const idlService = IDL.Service({
  'castVote' : IDL.Func(
      [PollId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(VoteTally), 'err' : IDL.Text })],
      [],
    ),
  'createPoll' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(FaceMarker),
        PollCategory,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : PollPublic, 'err' : IDL.Text })],
      [],
    ),
  'createProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ProfilePublic, 'err' : IDL.Text })],
      [],
    ),
  'getMyPolls' : IDL.Func([], [IDL.Vec(PollSummary)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(ProfilePublic)], ['query']),
  'getPoll' : IDL.Func([PollId], [IDL.Opt(PollPublic)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(ProfilePublic)], ['query']),
  'getPublicFeed' : IDL.Func([IDL.Nat], [IDL.Vec(PollSummary)], ['query']),
  'getResults' : IDL.Func([PollId], [IDL.Opt(IDL.Vec(VoteTally))], ['query']),
  'hasVoted' : IDL.Func([PollId], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PollId = IDL.Text;
  const VoteTally = IDL.Record({
    'count' : IDL.Nat,
    'faceNumber' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  const FaceMarker = IDL.Record({
    'xPercent' : IDL.Float64,
    'yPercent' : IDL.Float64,
    'faceNumber' : IDL.Nat,
  });
  const PollCategory = IDL.Variant({
    'mostCharming' : IDL.Null,
    'mostPhotogenic' : IDL.Null,
    'bestSmile' : IDL.Null,
    'bestStyle' : IDL.Null,
    'mostHandsome' : IDL.Null,
    'mostConfident' : IDL.Null,
    'mostAttractive' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const PollPublic = IDL.Record({
    'id' : PollId,
    'creator' : UserId,
    'expiresAt' : Timestamp,
    'votes' : IDL.Vec(VoteTally),
    'totalVotes' : IDL.Nat,
    'createdAt' : Timestamp,
    'isAnonymous' : IDL.Bool,
    'photoUrl' : IDL.Text,
    'faceMarkers' : IDL.Vec(FaceMarker),
    'caption' : IDL.Opt(IDL.Text),
    'category' : PollCategory,
  });
  const ProfilePublic = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'pollCount' : IDL.Nat,
  });
  const PollSummary = IDL.Record({
    'id' : PollId,
    'leadingFace' : IDL.Opt(IDL.Nat),
    'expiresAt' : Timestamp,
    'totalVotes' : IDL.Nat,
    'photoUrl' : IDL.Text,
    'caption' : IDL.Opt(IDL.Text),
    'category' : PollCategory,
  });
  
  return IDL.Service({
    'castVote' : IDL.Func(
        [PollId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(VoteTally), 'err' : IDL.Text })],
        [],
      ),
    'createPoll' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(FaceMarker),
          PollCategory,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : PollPublic, 'err' : IDL.Text })],
        [],
      ),
    'createProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ProfilePublic, 'err' : IDL.Text })],
        [],
      ),
    'getMyPolls' : IDL.Func([], [IDL.Vec(PollSummary)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(ProfilePublic)], ['query']),
    'getPoll' : IDL.Func([PollId], [IDL.Opt(PollPublic)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(ProfilePublic)], ['query']),
    'getPublicFeed' : IDL.Func([IDL.Nat], [IDL.Vec(PollSummary)], ['query']),
    'getResults' : IDL.Func([PollId], [IDL.Opt(IDL.Vec(VoteTally))], ['query']),
    'hasVoted' : IDL.Func([PollId], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };