/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface PollPublic {
    id: PollId;
    creator: UserId;
    expiresAt: Timestamp;
    votes: Array<VoteTally>;
    totalVotes: bigint;
    createdAt: Timestamp;
    isAnonymous: boolean;
    photoUrl: string;
    faceMarkers: Array<FaceMarker>;
    caption?: string;
    category: PollCategory;
}
export interface FaceMarker {
    xPercent: number;
    yPercent: number;
    faceNumber: bigint;
}
export interface VoteTally {
    count: bigint;
    faceNumber: bigint;
    percentage: number;
}
export interface PollSummary {
    id: PollId;
    leadingFace?: bigint;
    expiresAt: Timestamp;
    totalVotes: bigint;
    photoUrl: string;
    caption?: string;
    category: PollCategory;
}
export type PollId = string;
export interface ProfilePublic {
    id: UserId;
    username: string;
    createdAt: Timestamp;
    pollCount: bigint;
}
export enum PollCategory {
    mostCharming = "mostCharming",
    mostPhotogenic = "mostPhotogenic",
    bestSmile = "bestSmile",
    bestStyle = "bestStyle",
    mostHandsome = "mostHandsome",
    mostConfident = "mostConfident",
    mostAttractive = "mostAttractive"
}
export interface backendInterface {
    castVote(pollId: PollId, faceNumber: bigint): Promise<{
        __kind__: "ok";
        ok: Array<VoteTally>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createPoll(photoUrl: string, faceMarkers: Array<FaceMarker>, category: PollCategory, durationHours: bigint, caption: string | null, isAnonymous: boolean): Promise<{
        __kind__: "ok";
        ok: PollPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createProfile(username: string): Promise<{
        __kind__: "ok";
        ok: ProfilePublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyPolls(): Promise<Array<PollSummary>>;
    getMyProfile(): Promise<ProfilePublic | null>;
    getPoll(pollId: PollId): Promise<PollPublic | null>;
    getProfile(userId: UserId): Promise<ProfilePublic | null>;
    getPublicFeed(page: bigint): Promise<Array<PollSummary>>;
    getResults(pollId: PollId): Promise<Array<VoteTally> | null>;
    hasVoted(pollId: PollId): Promise<boolean>;
}
import type { FaceMarker as _FaceMarker, PollCategory as _PollCategory, PollId as _PollId, PollPublic as _PollPublic, PollSummary as _PollSummary, ProfilePublic as _ProfilePublic, Timestamp as _Timestamp, UserId as _UserId, VoteTally as _VoteTally } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async castVote(arg0: PollId, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: Array<VoteTally>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.castVote(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castVote(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPoll(arg0: string, arg1: Array<FaceMarker>, arg2: PollCategory, arg3: bigint, arg4: string | null, arg5: boolean): Promise<{
        __kind__: "ok";
        ok: PollPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0, arg1, to_candid_PollCategory_n2(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0, arg1, to_candid_PollCategory_n2(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProfile(arg0: string): Promise<{
        __kind__: "ok";
        ok: ProfilePublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPolls(): Promise<Array<PollSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPolls();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPolls();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<ProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoll(arg0: PollId): Promise<PollPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoll(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoll(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<ProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicFeed(arg0: bigint): Promise<Array<PollSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicFeed(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicFeed(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResults(arg0: PollId): Promise<Array<VoteTally> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResults(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResults(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasVoted(arg0: PollId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasVoted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasVoted(arg0);
            return result;
        }
    }
}
function from_candid_PollCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PollCategory): PollCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PollPublic_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PollPublic): PollPublic {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PollSummary_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PollSummary): PollSummary {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfilePublic]): ProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PollPublic]): PollPublic | null {
    return value.length === 0 ? null : from_candid_PollPublic_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_VoteTally>]): Array<VoteTally> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PollId;
    leadingFace: [] | [bigint];
    expiresAt: _Timestamp;
    totalVotes: bigint;
    photoUrl: string;
    caption: [] | [string];
    category: _PollCategory;
}): {
    id: PollId;
    leadingFace?: bigint;
    expiresAt: Timestamp;
    totalVotes: bigint;
    photoUrl: string;
    caption?: string;
    category: PollCategory;
} {
    return {
        id: value.id,
        leadingFace: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.leadingFace)),
        expiresAt: value.expiresAt,
        totalVotes: value.totalVotes,
        photoUrl: value.photoUrl,
        caption: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.caption)),
        category: from_candid_PollCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PollId;
    creator: _UserId;
    expiresAt: _Timestamp;
    votes: Array<_VoteTally>;
    totalVotes: bigint;
    createdAt: _Timestamp;
    isAnonymous: boolean;
    photoUrl: string;
    faceMarkers: Array<_FaceMarker>;
    caption: [] | [string];
    category: _PollCategory;
}): {
    id: PollId;
    creator: UserId;
    expiresAt: Timestamp;
    votes: Array<VoteTally>;
    totalVotes: bigint;
    createdAt: Timestamp;
    isAnonymous: boolean;
    photoUrl: string;
    faceMarkers: Array<FaceMarker>;
    caption?: string;
    category: PollCategory;
} {
    return {
        id: value.id,
        creator: value.creator,
        expiresAt: value.expiresAt,
        votes: value.votes,
        totalVotes: value.totalVotes,
        createdAt: value.createdAt,
        isAnonymous: value.isAnonymous,
        photoUrl: value.photoUrl,
        faceMarkers: value.faceMarkers,
        caption: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.caption)),
        category: from_candid_PollCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_VoteTally>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<VoteTally>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mostCharming: null;
} | {
    mostPhotogenic: null;
} | {
    bestSmile: null;
} | {
    bestStyle: null;
} | {
    mostHandsome: null;
} | {
    mostConfident: null;
} | {
    mostAttractive: null;
}): PollCategory {
    return "mostCharming" in value ? PollCategory.mostCharming : "mostPhotogenic" in value ? PollCategory.mostPhotogenic : "bestSmile" in value ? PollCategory.bestSmile : "bestStyle" in value ? PollCategory.bestStyle : "mostHandsome" in value ? PollCategory.mostHandsome : "mostConfident" in value ? PollCategory.mostConfident : "mostAttractive" in value ? PollCategory.mostAttractive : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProfilePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ProfilePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PollPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PollPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PollPublic_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PollSummary>): Array<PollSummary> {
    return value.map((x)=>from_candid_PollSummary_n13(_uploadFile, _downloadFile, x));
}
function to_candid_PollCategory_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PollCategory): _PollCategory {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PollCategory): {
    mostCharming: null;
} | {
    mostPhotogenic: null;
} | {
    bestSmile: null;
} | {
    bestStyle: null;
} | {
    mostHandsome: null;
} | {
    mostConfident: null;
} | {
    mostAttractive: null;
} {
    return value == PollCategory.mostCharming ? {
        mostCharming: null
    } : value == PollCategory.mostPhotogenic ? {
        mostPhotogenic: null
    } : value == PollCategory.bestSmile ? {
        bestSmile: null
    } : value == PollCategory.bestStyle ? {
        bestStyle: null
    } : value == PollCategory.mostHandsome ? {
        mostHandsome: null
    } : value == PollCategory.mostConfident ? {
        mostConfident: null
    } : value == PollCategory.mostAttractive ? {
        mostAttractive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
